/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_aowindow_menu (void);
GtkWidget* create_aowindow_formulaire (void);
GtkWidget* create_aowindow_dep_succ (void);
GtkWidget* create_aowindow_consult (void);
GtkWidget* create_aowindow_c_supp (void);
GtkWidget* create_aowindow_cs (void);
GtkWidget* create_aowindow_service (void);
