/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_FJmodifier (void);
GtkWidget* create_FJajouter (void);
GtkWidget* create_FJsupprimer (void);
GtkWidget* create_FJchercher (void);
GtkWidget* create_FJrupturedestock (void);
GtkWidget* create_FJafficher21 (void);
