/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *FJmodifier;
  GtkWidget *FJajouter;
  GtkWidget *FJsupprimer;
  GtkWidget *FJchercher;
  GtkWidget *FJrupturedestock;
  GtkWidget *FJafficher21;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  FJmodifier = create_FJmodifier ();
  gtk_widget_show (FJmodifier);
  FJajouter = create_FJajouter ();
  gtk_widget_show (FJajouter);
  FJsupprimer = create_FJsupprimer ();
  gtk_widget_show (FJsupprimer);
  FJchercher = create_FJchercher ();
  gtk_widget_show (FJchercher);
  FJrupturedestock = create_FJrupturedestock ();
  gtk_widget_show (FJrupturedestock);
  FJafficher21 = create_FJafficher21 ();
  gtk_widget_show (FJafficher21);

  gtk_main ();
  return 0;
}

