/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fowindowauthen (void);
GtkWidget* create_fowindowen (void);
GtkWidget* create_fowindowaffiche (void);
GtkWidget* create_fowindowajouter (void);
GtkWidget* create_fowindowmodifier (void);
GtkWidget* create_fowindowchercher (void);
GtkWidget* create_fowindowsupp (void);
