/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowgestionetudiant (void);
GtkWidget* create_windowmodifier (void);
GtkWidget* create_windowafficher (void);
GtkWidget* create_windowafficherniveau (void);
GtkWidget* create_windowerror1 (void);
GtkWidget* create_windowerror2 (void);
GtkWidget* create_windowok (void);
GtkWidget* create_fowindowen (void);
GtkWidget* create_fowindowaffiche (void);
GtkWidget* create_fowindowajouter (void);
GtkWidget* create_fowindowmodifier (void);
GtkWidget* create_fowindowchercher (void);
GtkWidget* create_fowindowsupp (void);
GtkWidget* create_cawindowlogin (void);
GtkWidget* create_cawindowgdc (void);
GtkWidget* create_cawindowsecurit__ (void);
GtkWidget* create_cawindowet (void);
GtkWidget* create_cawindowajouter (void);
GtkWidget* create_cawindowmodifier (void);
GtkWidget* create_cawindowtache (void);
GtkWidget* create_acwrechercher (void);
GtkWidget* create_acwindowsupprimer (void);
GtkWidget* create_FJmodifier (void);
GtkWidget* create_FJajouter (void);
GtkWidget* create_FJsupprimer (void);
GtkWidget* create_FJchercher (void);
GtkWidget* create_FJrupturedestock (void);
GtkWidget* create_FJafficher21 (void);
GtkWidget* create_aowindow_menu (void);
GtkWidget* create_aowindow_formulaire (void);
GtkWidget* create_aowindow_dep_succ (void);
GtkWidget* create_aowindow_consult (void);
GtkWidget* create_aowindow_c_supp (void);
GtkWidget* create_aowindow_cs (void);
GtkWidget* create_aowindow_service (void);
GtkWidget* create_bk_welcome (void);
GtkWidget* create_bk_aff (void);
GtkWidget* create_bk_add (void);
GtkWidget* create_bk_modifier (void);
GtkWidget* create_bk_liste (void);
