/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  /*GtkWidget *windowgestionetudiant;
  GtkWidget *windowmodifier;
  GtkWidget *windowafficher;
  GtkWidget *windowafficherniveau;
  GtkWidget *windowerror1;
  GtkWidget *windowerror2;
  GtkWidget *windowok;
  GtkWidget *fowindowen;
  GtkWidget *fowindowaffiche;
  GtkWidget *fowindowajouter;
  GtkWidget *fowindowmodifier;
  GtkWidget *fowindowchercher;
  GtkWidget *fowindowsupp;
  GtkWidget *cawindowlogin;
  GtkWidget *cawindowgdc;
  GtkWidget *cawindowsecurit__;
  GtkWidget *cawindowet;
  GtkWidget *cawindowajouter;
  GtkWidget *cawindowmodifier;*/
  GtkWidget *cawindowtache;
  /*GtkWidget *acwrechercher;
  GtkWidget *acwindowsupprimer;
  GtkWidget *FJmodifier;
  GtkWidget *FJajouter;
  GtkWidget *FJsupprimer;
  GtkWidget *FJchercher;
  GtkWidget *FJrupturedestock;
  GtkWidget *FJafficher21;
  GtkWidget *aowindow_menu;
  GtkWidget *aowindow_formulaire;
  GtkWidget *aowindow_dep_succ;
  GtkWidget *aowindow_consult;
  GtkWidget *aowindow_c_supp;
  GtkWidget *aowindow_cs;
  GtkWidget *aowindow_service;*/

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*windowgestionetudiant = create_windowgestionetudiant ();
  gtk_widget_show (windowgestionetudiant);
  windowmodifier = create_windowmodifier ();
  gtk_widget_show (windowmodifier);
  windowafficher = create_windowafficher ();
  gtk_widget_show (windowafficher);
  windowafficherniveau = create_windowafficherniveau ();
  gtk_widget_show (windowafficherniveau);
  windowerror1 = create_windowerror1 ();
  gtk_widget_show (windowerror1);
  windowerror2 = create_windowerror2 ();
  gtk_widget_show (windowerror2);
  windowok = create_windowok ();
  gtk_widget_show (windowok);
  fowindowen = create_fowindowen ();
  gtk_widget_show (fowindowen);
  fowindowaffiche = create_fowindowaffiche ();
  gtk_widget_show (fowindowaffiche);
  fowindowajouter = create_fowindowajouter ();
  gtk_widget_show (fowindowajouter);
  fowindowmodifier = create_fowindowmodifier ();
  gtk_widget_show (fowindowmodifier);
  fowindowchercher = create_fowindowchercher ();
  gtk_widget_show (fowindowchercher);
  fowindowsupp = create_fowindowsupp ();
  gtk_widget_show (fowindowsupp);
  cawindowlogin = create_cawindowlogin ();
  gtk_widget_show (cawindowlogin);
  cawindowgdc = create_cawindowgdc ();
  gtk_widget_show (cawindowgdc);
  cawindowsecurit__ = create_cawindowsecurit__ ();
  gtk_widget_show (cawindowsecurit__);
  cawindowet = create_cawindowet ();
  gtk_widget_show (cawindowet);
  cawindowajouter = create_cawindowajouter ();
  gtk_widget_show (cawindowajouter);
  cawindowmodifier = create_cawindowmodifier ();
  gtk_widget_show (cawindowmodifier);*/
  cawindowtache = create_cawindowtache ();
  gtk_widget_show (cawindowtache);
  /*acwrechercher = create_acwrechercher ();
  gtk_widget_show (acwrechercher);
  acwindowsupprimer = create_acwindowsupprimer ();
  gtk_widget_show (acwindowsupprimer);
  FJmodifier = create_FJmodifier ();
  gtk_widget_show (FJmodifier);
  FJajouter = create_FJajouter ();
  gtk_widget_show (FJajouter);
  FJsupprimer = create_FJsupprimer ();
  gtk_widget_show (FJsupprimer);
  FJchercher = create_FJchercher ();
  gtk_widget_show (FJchercher);
  FJrupturedestock = create_FJrupturedestock ();
  gtk_widget_show (FJrupturedestock);
  FJafficher21 = create_FJafficher21 ();
  gtk_widget_show (FJafficher21);
  aowindow_menu = create_aowindow_menu ();
  gtk_widget_show (aowindow_menu);
  aowindow_formulaire = create_aowindow_formulaire ();
  gtk_widget_show (aowindow_formulaire);
  aowindow_dep_succ = create_aowindow_dep_succ ();
  gtk_widget_show (aowindow_dep_succ);
  aowindow_consult = create_aowindow_consult ();
  gtk_widget_show (aowindow_consult);
  aowindow_c_supp = create_aowindow_c_supp ();
  gtk_widget_show (aowindow_c_supp);
  aowindow_cs = create_aowindow_cs ();
  gtk_widget_show (aowindow_cs);
  aowindow_service = create_aowindow_service ();
  gtk_widget_show (aowindow_service);*/

  gtk_main ();
  return 0;
}

