/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowgestionetudiant (void);
GtkWidget* create_windowmodifier (void);
GtkWidget* create_windowafficher (void);
GtkWidget* create_windowafficherniveau (void);
GtkWidget* create_windowerror1 (void);
GtkWidget* create_windowerror2 (void);
GtkWidget* create_windowok (void);
