/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowgestionetudiant (void)
{
  GtkWidget *windowgestionetudiant;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *entrynomaj;
  GtkWidget *entrycinaj;
  GtkWidget *entryprenomaj;
  GtkWidget *entrytelephoneaj;
  GtkObject *spinbuttonjouraj_adj;
  GtkWidget *spinbuttonjouraj;
  GtkObject *spinbuttonmoisaj_adj;
  GtkWidget *spinbuttonmoisaj;
  GtkObject *spinbuttonanneeaj_adj;
  GtkWidget *spinbuttonanneeaj;
  GtkWidget *labeljour;
  GtkWidget *labelmois;
  GtkWidget *labelannee;
  GtkWidget *Ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label4;
  GtkWidget *afficheraj;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label5;
  GtkWidget *labelcinaj;
  GtkWidget *comboboxblockaj;
  GtkWidget *rbfemme;
  GSList *rbfemme_group = NULL;
  GtkWidget *comboboxniveauaj;
  GtkWidget *labeldatedenaissanceaj;
  GtkWidget *rbhomme;
  GtkWidget *labelnomaj;
  GtkWidget *labelprenomaj;
  GtkWidget *labelniveauaj;
  GtkWidget *labelblockaj;
  GtkWidget *labeltelephoneaj;
  GtkWidget *labelsexaj;
  GtkWidget *labelinscriptionaj;
  GtkWidget *tabajouter;

  windowgestionetudiant = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowgestionetudiant, 1160, 600);
  gtk_window_set_title (GTK_WINDOW (windowgestionetudiant), _("Ajouter un etudiant"));
  gtk_window_set_position (GTK_WINDOW (windowgestionetudiant), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (windowgestionetudiant), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowgestionetudiant), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 1152, 784);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  entrynomaj = gtk_entry_new ();
  gtk_widget_show (entrynomaj);
  gtk_fixed_put (GTK_FIXED (fixed2), entrynomaj, 225, 150);
  gtk_widget_set_size_request (entrynomaj, 180, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynomaj), 8226);

  entrycinaj = gtk_entry_new ();
  gtk_widget_show (entrycinaj);
  gtk_fixed_put (GTK_FIXED (fixed2), entrycinaj, 480, 70);
  gtk_widget_set_size_request (entrycinaj, 180, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycinaj), 8226);

  entryprenomaj = gtk_entry_new ();
  gtk_widget_show (entryprenomaj);
  gtk_fixed_put (GTK_FIXED (fixed2), entryprenomaj, 225, 240);
  gtk_widget_set_size_request (entryprenomaj, 180, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenomaj), 8226);

  entrytelephoneaj = gtk_entry_new ();
  gtk_widget_show (entrytelephoneaj);
  gtk_fixed_put (GTK_FIXED (fixed2), entrytelephoneaj, 888, 430);
  gtk_widget_set_size_request (entrytelephoneaj, 180, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrytelephoneaj), 8226);

  spinbuttonjouraj_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonjouraj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonjouraj_adj), 1, 0);
  gtk_widget_show (spinbuttonjouraj);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonjouraj, 808, 330);
  gtk_widget_set_size_request (spinbuttonjouraj, 60, 30);

  spinbuttonmoisaj_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmoisaj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmoisaj_adj), 1, 0);
  gtk_widget_show (spinbuttonmoisaj);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonmoisaj, 912, 330);
  gtk_widget_set_size_request (spinbuttonmoisaj, 60, 30);

  spinbuttonanneeaj_adj = gtk_adjustment_new (1980, 1980, 2050, 1, 10, 10);
  spinbuttonanneeaj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonanneeaj_adj), 1, 0);
  gtk_widget_show (spinbuttonanneeaj);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonanneeaj, 1024, 330);
  gtk_widget_set_size_request (spinbuttonanneeaj, 60, 30);

  labeljour = gtk_label_new (_("jour"));
  gtk_widget_show (labeljour);
  gtk_fixed_put (GTK_FIXED (fixed2), labeljour, 808, 312);
  gtk_widget_set_size_request (labeljour, 57, 24);

  labelmois = gtk_label_new (_("mois"));
  gtk_widget_show (labelmois);
  gtk_fixed_put (GTK_FIXED (fixed2), labelmois, 912, 312);
  gtk_widget_set_size_request (labelmois, 57, 24);

  labelannee = gtk_label_new (_("annee"));
  gtk_widget_show (labelannee);
  gtk_fixed_put (GTK_FIXED (fixed2), labelannee, 1024, 312);
  gtk_widget_set_size_request (labelannee, 57, 24);

  Ajouter = gtk_button_new ();
  gtk_widget_show (Ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), Ajouter, 488, 504);
  gtk_widget_set_size_request (Ajouter, 190, 60);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (Ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_(" Ajouter"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox1), label4, FALSE, FALSE, 0);

  afficheraj = gtk_button_new ();
  gtk_widget_show (afficheraj);
  gtk_fixed_put (GTK_FIXED (fixed2), afficheraj, 952, 8);
  gtk_widget_set_size_request (afficheraj, 190, 60);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (afficheraj), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_(" gestion des \303\251tudiants"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);

  labelcinaj = gtk_label_new (_("cin"));
  gtk_widget_show (labelcinaj);
  gtk_fixed_put (GTK_FIXED (fixed2), labelcinaj, 344, 72);
  gtk_widget_set_size_request (labelcinaj, 136, 32);

  comboboxblockaj = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxblockaj);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxblockaj, 225, 430);
  gtk_widget_set_size_request (comboboxblockaj, 180, 40);
  GTK_WIDGET_SET_FLAGS (comboboxblockaj, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (comboboxblockaj, GTK_CAN_DEFAULT);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxblockaj), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxblockaj), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxblockaj), _("3"));
  gtk_combo_box_set_focus_on_click (GTK_COMBO_BOX (comboboxblockaj), FALSE);

  rbfemme = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (rbfemme);
  gtk_fixed_put (GTK_FIXED (fixed2), rbfemme, 944, 200);
  gtk_widget_set_size_request (rbfemme, 80, 25);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbfemme), rbfemme_group);
  rbfemme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbfemme));

  comboboxniveauaj = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxniveauaj);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxniveauaj, 225, 330);
  gtk_widget_set_size_request (comboboxniveauaj, 180, 40);
  GTK_WIDGET_SET_FLAGS (comboboxniveauaj, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (comboboxniveauaj, GTK_CAN_DEFAULT);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveauaj), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveauaj), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveauaj), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveauaj), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveauaj), _("5"));
  gtk_combo_box_set_focus_on_click (GTK_COMBO_BOX (comboboxniveauaj), FALSE);

  labeldatedenaissanceaj = gtk_label_new (_("date de naissance"));
  gtk_widget_show (labeldatedenaissanceaj);
  gtk_fixed_put (GTK_FIXED (fixed2), labeldatedenaissanceaj, 848, 260);
  gtk_widget_set_size_request (labeldatedenaissanceaj, 168, 56);

  rbhomme = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (rbhomme);
  gtk_fixed_put (GTK_FIXED (fixed2), rbhomme, 816, 200);
  gtk_widget_set_size_request (rbhomme, 80, 25);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbhomme), rbfemme_group);
  rbfemme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbhomme));

  labelnomaj = gtk_label_new (_("nom"));
  gtk_widget_show (labelnomaj);
  gtk_fixed_put (GTK_FIXED (fixed2), labelnomaj, 90, 150);
  gtk_widget_set_size_request (labelnomaj, 170, 40);

  labelprenomaj = gtk_label_new (_("prenom"));
  gtk_widget_show (labelprenomaj);
  gtk_fixed_put (GTK_FIXED (fixed2), labelprenomaj, 90, 240);
  gtk_widget_set_size_request (labelprenomaj, 170, 40);

  labelniveauaj = gtk_label_new (_("niveau"));
  gtk_widget_show (labelniveauaj);
  gtk_fixed_put (GTK_FIXED (fixed2), labelniveauaj, 90, 330);
  gtk_widget_set_size_request (labelniveauaj, 170, 40);

  labelblockaj = gtk_label_new (_("block"));
  gtk_widget_show (labelblockaj);
  gtk_fixed_put (GTK_FIXED (fixed2), labelblockaj, 90, 430);
  gtk_widget_set_size_request (labelblockaj, 170, 40);

  labeltelephoneaj = gtk_label_new (_("telephone"));
  gtk_widget_show (labeltelephoneaj);
  gtk_fixed_put (GTK_FIXED (fixed2), labeltelephoneaj, 750, 430);
  gtk_widget_set_size_request (labeltelephoneaj, 170, 40);

  labelsexaj = gtk_label_new (_("Sex"));
  gtk_widget_show (labelsexaj);
  gtk_fixed_put (GTK_FIXED (fixed2), labelsexaj, 825, 150);
  gtk_widget_set_size_request (labelsexaj, 170, 40);
  gtk_misc_set_alignment (GTK_MISC (labelsexaj), 0.5, 0.4);

  labelinscriptionaj = gtk_label_new (_("Inscription"));
  gtk_widget_show (labelinscriptionaj);
  gtk_fixed_put (GTK_FIXED (fixed2), labelinscriptionaj, 448, 0);
  gtk_widget_set_size_request (labelinscriptionaj, 250, 50);

  tabajouter = gtk_label_new (_("Ajouter"));
  gtk_widget_show (tabajouter);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), tabajouter);

  g_signal_connect ((gpointer) entrycinaj, "grab_focus",
                    G_CALLBACK (on_entrycinaj_grab_focus),
                    NULL);
  g_signal_connect ((gpointer) Ajouter, "clicked",
                    G_CALLBACK (on_Ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficheraj, "clicked",
                    G_CALLBACK (on_afficheraj_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbfemme, "toggled",
                    G_CALLBACK (on_rbfemme_toggled),
                    NULL);
  g_signal_connect ((gpointer) rbhomme, "toggled",
                    G_CALLBACK (on_rbhomme_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowgestionetudiant, windowgestionetudiant, "windowgestionetudiant");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, entrynomaj, "entrynomaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, entrycinaj, "entrycinaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, entryprenomaj, "entryprenomaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, entrytelephoneaj, "entrytelephoneaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, spinbuttonjouraj, "spinbuttonjouraj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, spinbuttonmoisaj, "spinbuttonmoisaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, spinbuttonanneeaj, "spinbuttonanneeaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, labeljour, "labeljour");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, labelmois, "labelmois");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, labelannee, "labelannee");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, Ajouter, "Ajouter");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, label4, "label4");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, afficheraj, "afficheraj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, label5, "label5");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, labelcinaj, "labelcinaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, comboboxblockaj, "comboboxblockaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, rbfemme, "rbfemme");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, comboboxniveauaj, "comboboxniveauaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, labeldatedenaissanceaj, "labeldatedenaissanceaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, rbhomme, "rbhomme");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, labelnomaj, "labelnomaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, labelprenomaj, "labelprenomaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, labelniveauaj, "labelniveauaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, labelblockaj, "labelblockaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, labeltelephoneaj, "labeltelephoneaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, labelsexaj, "labelsexaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, labelinscriptionaj, "labelinscriptionaj");
  GLADE_HOOKUP_OBJECT (windowgestionetudiant, tabajouter, "tabajouter");

  return windowgestionetudiant;
}

GtkWidget*
create_windowmodifier (void)
{
  GtkWidget *windowmodifier;
  GtkWidget *fixed6;
  GtkWidget *entrytelephonemo;
  GtkWidget *entryprenommo;
  GtkWidget *entrynommo;
  GtkWidget *labelblock;
  GtkWidget *labelnom;
  GtkWidget *labelsex;
  GtkObject *spinbuttonjourmo_adj;
  GtkWidget *spinbuttonjourmo;
  GtkObject *spinbuttonmoismo_adj;
  GtkWidget *spinbuttonmoismo;
  GtkObject *spinbuttonanneemo_adj;
  GtkWidget *spinbuttonanneemo;
  GtkWidget *label14;
  GtkWidget *labelannee;
  GtkWidget *labelmois;
  GtkWidget *labeldatedenaissance;
  GtkWidget *labeltelephone;
  GtkWidget *labelprenom;
  GtkWidget *labelniveau;
  GtkWidget *rbhommemo;
  GSList *rbhommemo_group = NULL;
  GtkWidget *comboboxniveaumo;
  GtkWidget *comboboxblockmo;
  GtkWidget *rbfemmemo;
  GtkWidget *labeljour;
  GtkWidget *enregistrer;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label6;

  windowmodifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowmodifier, 800, 400);
  gtk_window_set_title (GTK_WINDOW (windowmodifier), _("modifier un etudiant"));
  gtk_window_set_position (GTK_WINDOW (windowmodifier), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (windowmodifier), FALSE);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (windowmodifier), fixed6);

  entrytelephonemo = gtk_entry_new ();
  gtk_widget_show (entrytelephonemo);
  gtk_fixed_put (GTK_FIXED (fixed6), entrytelephonemo, 530, 160);
  gtk_widget_set_size_request (entrytelephonemo, 160, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrytelephonemo), 8226);

  entryprenommo = gtk_entry_new ();
  gtk_widget_show (entryprenommo);
  gtk_fixed_put (GTK_FIXED (fixed6), entryprenommo, 150, 160);
  gtk_widget_set_size_request (entryprenommo, 160, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenommo), 8226);

  entrynommo = gtk_entry_new ();
  gtk_widget_show (entrynommo);
  gtk_fixed_put (GTK_FIXED (fixed6), entrynommo, 150, 95);
  gtk_widget_set_size_request (entrynommo, 160, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynommo), 8226);

  labelblock = gtk_label_new (_("block"));
  gtk_widget_show (labelblock);
  gtk_fixed_put (GTK_FIXED (fixed6), labelblock, 456, 104);
  gtk_widget_set_size_request (labelblock, 49, 17);

  labelnom = gtk_label_new (_("nom"));
  gtk_widget_show (labelnom);
  gtk_fixed_put (GTK_FIXED (fixed6), labelnom, 80, 96);
  gtk_widget_set_size_request (labelnom, 49, 17);

  labelsex = gtk_label_new (_("sex"));
  gtk_widget_show (labelsex);
  gtk_fixed_put (GTK_FIXED (fixed6), labelsex, 72, 216);
  gtk_widget_set_size_request (labelsex, 41, 17);

  spinbuttonjourmo_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonjourmo = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonjourmo_adj), 1, 0);
  gtk_widget_show (spinbuttonjourmo);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonjourmo, 530, 260);
  gtk_widget_set_size_request (spinbuttonjourmo, 60, 30);

  spinbuttonmoismo_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmoismo = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmoismo_adj), 1, 0);
  gtk_widget_show (spinbuttonmoismo);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonmoismo, 625, 260);
  gtk_widget_set_size_request (spinbuttonmoismo, 60, 30);

  spinbuttonanneemo_adj = gtk_adjustment_new (1980, 1980, 2050, 1, 10, 10);
  spinbuttonanneemo = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonanneemo_adj), 1, 0);
  gtk_widget_show (spinbuttonanneemo);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonanneemo, 720, 260);
  gtk_widget_set_size_request (spinbuttonanneemo, 60, 30);

  label14 = gtk_label_new (_("Modification"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed6), label14, 296, 16);
  gtk_widget_set_size_request (label14, 184, 48);

  labelannee = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (labelannee);
  gtk_fixed_put (GTK_FIXED (fixed6), labelannee, 720, 232);
  gtk_widget_set_size_request (labelannee, 64, 24);

  labelmois = gtk_label_new (_("mois"));
  gtk_widget_show (labelmois);
  gtk_fixed_put (GTK_FIXED (fixed6), labelmois, 624, 232);
  gtk_widget_set_size_request (labelmois, 48, 24);

  labeldatedenaissance = gtk_label_new (_("date de naissance"));
  gtk_widget_show (labeldatedenaissance);
  gtk_fixed_put (GTK_FIXED (fixed6), labeldatedenaissance, 392, 256);
  gtk_widget_set_size_request (labeldatedenaissance, 136, 32);

  labeltelephone = gtk_label_new (_("telephone"));
  gtk_widget_show (labeltelephone);
  gtk_fixed_put (GTK_FIXED (fixed6), labeltelephone, 424, 160);
  gtk_widget_set_size_request (labeltelephone, 104, 24);

  labelprenom = gtk_label_new (_("prenom"));
  gtk_widget_show (labelprenom);
  gtk_fixed_put (GTK_FIXED (fixed6), labelprenom, 72, 168);
  gtk_widget_set_size_request (labelprenom, 64, 24);

  labelniveau = gtk_label_new (_("niveau"));
  gtk_widget_show (labelniveau);
  gtk_fixed_put (GTK_FIXED (fixed6), labelniveau, 72, 264);
  gtk_widget_set_size_request (labelniveau, 72, 24);

  rbhommemo = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (rbhommemo);
  gtk_fixed_put (GTK_FIXED (fixed6), rbhommemo, 150, 215);
  gtk_widget_set_size_request (rbhommemo, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbhommemo), rbhommemo_group);
  rbhommemo_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbhommemo));

  comboboxniveaumo = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxniveaumo);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxniveaumo, 150, 260);
  gtk_widget_set_size_request (comboboxniveaumo, 160, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveaumo), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveaumo), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveaumo), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveaumo), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveaumo), _("5"));

  comboboxblockmo = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxblockmo);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxblockmo, 530, 95);
  gtk_widget_set_size_request (comboboxblockmo, 160, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxblockmo), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxblockmo), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxblockmo), _("3"));

  rbfemmemo = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (rbfemmemo);
  gtk_fixed_put (GTK_FIXED (fixed6), rbfemmemo, 264, 215);
  gtk_widget_set_size_request (rbfemmemo, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbfemmemo), rbhommemo_group);
  rbhommemo_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbfemmemo));

  labeljour = gtk_label_new (_("jour"));
  gtk_widget_show (labeljour);
  gtk_fixed_put (GTK_FIXED (fixed6), labeljour, 536, 232);
  gtk_widget_set_size_request (labeljour, 49, 24);

  enregistrer = gtk_button_new ();
  gtk_widget_show (enregistrer);
  gtk_fixed_put (GTK_FIXED (fixed6), enregistrer, 256, 328);
  gtk_widget_set_size_request (enregistrer, 232, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (enregistrer), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_(" Enregistrer les modifications"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) entrynommo, "grab_focus",
                    G_CALLBACK (on_entrynommo_grab_focus),
                    NULL);
  g_signal_connect ((gpointer) rbhommemo, "toggled",
                    G_CALLBACK (on_rbhommemo_toggled),
                    NULL);
  g_signal_connect ((gpointer) rbfemmemo, "toggled",
                    G_CALLBACK (on_rbfemmemo_toggled),
                    NULL);
  g_signal_connect ((gpointer) enregistrer, "clicked",
                    G_CALLBACK (on_enregistrer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowmodifier, windowmodifier, "windowmodifier");
  GLADE_HOOKUP_OBJECT (windowmodifier, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (windowmodifier, entrytelephonemo, "entrytelephonemo");
  GLADE_HOOKUP_OBJECT (windowmodifier, entryprenommo, "entryprenommo");
  GLADE_HOOKUP_OBJECT (windowmodifier, entrynommo, "entrynommo");
  GLADE_HOOKUP_OBJECT (windowmodifier, labelblock, "labelblock");
  GLADE_HOOKUP_OBJECT (windowmodifier, labelnom, "labelnom");
  GLADE_HOOKUP_OBJECT (windowmodifier, labelsex, "labelsex");
  GLADE_HOOKUP_OBJECT (windowmodifier, spinbuttonjourmo, "spinbuttonjourmo");
  GLADE_HOOKUP_OBJECT (windowmodifier, spinbuttonmoismo, "spinbuttonmoismo");
  GLADE_HOOKUP_OBJECT (windowmodifier, spinbuttonanneemo, "spinbuttonanneemo");
  GLADE_HOOKUP_OBJECT (windowmodifier, label14, "label14");
  GLADE_HOOKUP_OBJECT (windowmodifier, labelannee, "labelannee");
  GLADE_HOOKUP_OBJECT (windowmodifier, labelmois, "labelmois");
  GLADE_HOOKUP_OBJECT (windowmodifier, labeldatedenaissance, "labeldatedenaissance");
  GLADE_HOOKUP_OBJECT (windowmodifier, labeltelephone, "labeltelephone");
  GLADE_HOOKUP_OBJECT (windowmodifier, labelprenom, "labelprenom");
  GLADE_HOOKUP_OBJECT (windowmodifier, labelniveau, "labelniveau");
  GLADE_HOOKUP_OBJECT (windowmodifier, rbhommemo, "rbhommemo");
  GLADE_HOOKUP_OBJECT (windowmodifier, comboboxniveaumo, "comboboxniveaumo");
  GLADE_HOOKUP_OBJECT (windowmodifier, comboboxblockmo, "comboboxblockmo");
  GLADE_HOOKUP_OBJECT (windowmodifier, rbfemmemo, "rbfemmemo");
  GLADE_HOOKUP_OBJECT (windowmodifier, labeljour, "labeljour");
  GLADE_HOOKUP_OBJECT (windowmodifier, enregistrer, "enregistrer");
  GLADE_HOOKUP_OBJECT (windowmodifier, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowmodifier, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowmodifier, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowmodifier, label6, "label6");

  return windowmodifier;
}

GtkWidget*
create_windowafficher (void)
{
  GtkWidget *windowafficher;
  GtkWidget *fixed8;
  GtkWidget *treeview1;
  GtkWidget *entrycinre;
  GtkWidget *entryblockre;
  GtkWidget *rechercher;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label7;
  GtkWidget *actualiser;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label8;
  GtkWidget *supprimeraf;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label10;
  GtkWidget *modifieraf;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label9;
  GtkWidget *retour;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label12;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *niveau;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label11;

  windowafficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowafficher, 1165, 600);
  gtk_window_set_title (GTK_WINDOW (windowafficher), _("gestion des \303\251tudiants"));
  gtk_window_set_position (GTK_WINDOW (windowafficher), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (windowafficher), FALSE);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (windowafficher), fixed8);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview1, 48, 80);
  gtk_widget_set_size_request (treeview1, 872, 464);

  entrycinre = gtk_entry_new ();
  gtk_widget_show (entrycinre);
  gtk_fixed_put (GTK_FIXED (fixed8), entrycinre, 100, 25);
  gtk_widget_set_size_request (entrycinre, 180, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycinre), 8226);

  entryblockre = gtk_entry_new ();
  gtk_widget_show (entryblockre);
  gtk_fixed_put (GTK_FIXED (fixed8), entryblockre, 370, 25);
  gtk_widget_set_size_request (entryblockre, 180, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryblockre), 8226);

  rechercher = gtk_button_new ();
  gtk_widget_show (rechercher);
  gtk_fixed_put (GTK_FIXED (fixed8), rechercher, 560, 25);
  gtk_widget_set_size_request (rechercher, 150, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (rechercher), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_(" rechercher"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox4), label7, FALSE, FALSE, 0);

  actualiser = gtk_button_new ();
  gtk_widget_show (actualiser);
  gtk_fixed_put (GTK_FIXED (fixed8), actualiser, 768, 40);
  gtk_widget_set_size_request (actualiser, 150, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (actualiser), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_(" actualiser"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox5), label8, FALSE, FALSE, 0);

  supprimeraf = gtk_button_new ();
  gtk_widget_show (supprimeraf);
  gtk_fixed_put (GTK_FIXED (fixed8), supprimeraf, 925, 230);
  gtk_widget_set_size_request (supprimeraf, 230, 50);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (supprimeraf), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_(" supprimer"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox7), label10, FALSE, FALSE, 0);

  modifieraf = gtk_button_new ();
  gtk_widget_show (modifieraf);
  gtk_fixed_put (GTK_FIXED (fixed8), modifieraf, 925, 360);
  gtk_widget_set_size_request (modifieraf, 230, 50);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (modifieraf), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_(" modifier"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox6), label9, FALSE, FALSE, 0);

  retour = gtk_button_new ();
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed8), retour, 925, 490);
  gtk_widget_set_size_request (retour, 230, 50);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (retour), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_(" ajouter"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox9), label12, FALSE, FALSE, 0);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("cin"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton1, 40, 27);
  gtk_widget_set_size_request (checkbutton1, 118, 35);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("block"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton2, 300, 27);
  gtk_widget_set_size_request (checkbutton2, 118, 35);

  niveau = gtk_button_new ();
  gtk_widget_show (niveau);
  gtk_fixed_put (GTK_FIXED (fixed8), niveau, 925, 100);
  gtk_widget_set_size_request (niveau, 235, 50);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (niveau), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_(" nombre d'etudiants par niveau"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox8), label11, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) rechercher, "clicked",
                    G_CALLBACK (on_rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) actualiser, "clicked",
                    G_CALLBACK (on_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimeraf, "clicked",
                    G_CALLBACK (on_supprimeraf_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifieraf, "clicked",
                    G_CALLBACK (on_modifieraf_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour, "clicked",
                    G_CALLBACK (on_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) niveau, "clicked",
                    G_CALLBACK (on_niveau_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowafficher, windowafficher, "windowafficher");
  GLADE_HOOKUP_OBJECT (windowafficher, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (windowafficher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (windowafficher, entrycinre, "entrycinre");
  GLADE_HOOKUP_OBJECT (windowafficher, entryblockre, "entryblockre");
  GLADE_HOOKUP_OBJECT (windowafficher, rechercher, "rechercher");
  GLADE_HOOKUP_OBJECT (windowafficher, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowafficher, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowafficher, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowafficher, label7, "label7");
  GLADE_HOOKUP_OBJECT (windowafficher, actualiser, "actualiser");
  GLADE_HOOKUP_OBJECT (windowafficher, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windowafficher, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windowafficher, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowafficher, label8, "label8");
  GLADE_HOOKUP_OBJECT (windowafficher, supprimeraf, "supprimeraf");
  GLADE_HOOKUP_OBJECT (windowafficher, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (windowafficher, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (windowafficher, image7, "image7");
  GLADE_HOOKUP_OBJECT (windowafficher, label10, "label10");
  GLADE_HOOKUP_OBJECT (windowafficher, modifieraf, "modifieraf");
  GLADE_HOOKUP_OBJECT (windowafficher, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (windowafficher, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (windowafficher, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowafficher, label9, "label9");
  GLADE_HOOKUP_OBJECT (windowafficher, retour, "retour");
  GLADE_HOOKUP_OBJECT (windowafficher, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (windowafficher, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (windowafficher, image9, "image9");
  GLADE_HOOKUP_OBJECT (windowafficher, label12, "label12");
  GLADE_HOOKUP_OBJECT (windowafficher, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (windowafficher, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (windowafficher, niveau, "niveau");
  GLADE_HOOKUP_OBJECT (windowafficher, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (windowafficher, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (windowafficher, image8, "image8");
  GLADE_HOOKUP_OBJECT (windowafficher, label11, "label11");

  return windowafficher;
}

GtkWidget*
create_windowafficherniveau (void)
{
  GtkWidget *windowafficherniveau;
  GtkWidget *fixed9;
  GtkWidget *treeview2;
  GtkWidget *retourniveau;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label13;

  windowafficherniveau = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowafficherniveau, 530, 350);
  gtk_window_set_title (GTK_WINDOW (windowafficherniveau), _("nombre des etudiants par niveau"));
  gtk_window_set_position (GTK_WINDOW (windowafficherniveau), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (windowafficherniveau), FALSE);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (windowafficherniveau), fixed9);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed9), treeview2, 16, 72);
  gtk_widget_set_size_request (treeview2, 480, 136);

  retourniveau = gtk_button_new ();
  gtk_widget_show (retourniveau);
  gtk_fixed_put (GTK_FIXED (fixed9), retourniveau, 8, 8);
  gtk_widget_set_size_request (retourniveau, 88, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (retourniveau), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_(" retour"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox10), label13, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) retourniveau, "clicked",
                    G_CALLBACK (on_retourniveau_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowafficherniveau, windowafficherniveau, "windowafficherniveau");
  GLADE_HOOKUP_OBJECT (windowafficherniveau, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (windowafficherniveau, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (windowafficherniveau, retourniveau, "retourniveau");
  GLADE_HOOKUP_OBJECT (windowafficherniveau, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (windowafficherniveau, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (windowafficherniveau, image10, "image10");
  GLADE_HOOKUP_OBJECT (windowafficherniveau, label13, "label13");

  return windowafficherniveau;
}

GtkWidget*
create_windowerror1 (void)
{
  GtkWidget *windowerror1;
  GtkWidget *fixed10;
  GtkWidget *label1;

  windowerror1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowerror1, 500, 350);
  gtk_window_set_title (GTK_WINDOW (windowerror1), _("error"));
  gtk_window_set_position (GTK_WINDOW (windowerror1), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_resizable (GTK_WINDOW (windowerror1), FALSE);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (windowerror1), fixed10);

  label1 = gtk_label_new (_("veuillez verifier vos coordonn\303\251es"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed10), label1, 120, 120);
  gtk_widget_set_size_request (label1, 264, 96);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowerror1, windowerror1, "windowerror1");
  GLADE_HOOKUP_OBJECT (windowerror1, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (windowerror1, label1, "label1");

  return windowerror1;
}

GtkWidget*
create_windowerror2 (void)
{
  GtkWidget *windowerror2;
  GtkWidget *fixed11;
  GtkWidget *label2;

  windowerror2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowerror2, 500, 350);
  gtk_window_set_title (GTK_WINDOW (windowerror2), _("error"));
  gtk_window_set_position (GTK_WINDOW (windowerror2), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_resizable (GTK_WINDOW (windowerror2), FALSE);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (windowerror2), fixed11);

  label2 = gtk_label_new (_("cin existe deja"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed11), label2, 120, 120);
  gtk_widget_set_size_request (label2, 264, 96);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowerror2, windowerror2, "windowerror2");
  GLADE_HOOKUP_OBJECT (windowerror2, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (windowerror2, label2, "label2");

  return windowerror2;
}

GtkWidget*
create_windowok (void)
{
  GtkWidget *windowok;
  GtkWidget *fixed12;
  GtkWidget *label3;

  windowok = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowok, 500, 350);
  gtk_window_set_title (GTK_WINDOW (windowok), _("ok"));
  gtk_window_set_position (GTK_WINDOW (windowok), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_resizable (GTK_WINDOW (windowok), FALSE);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (windowok), fixed12);

  label3 = gtk_label_new (_("succes"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed12), label3, 120, 120);
  gtk_widget_set_size_request (label3, 264, 96);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowok, windowok, "windowok");
  GLADE_HOOKUP_OBJECT (windowok, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (windowok, label3, "label3");

  return windowok;
}

